### ISSUE TITLE
Have no v:progpath in older vim

### ISSUE THREAD

**Issue by amerlyq** [chrisbra/Recover.vim#37]
```
E121: Undefined variable: v:progpath
```
Seems it was introduced it in 7.4.234, see http://ftp.nluug.nl/editors/vim/patches/7.4/7.4.234
That var is cool, as you don't even have to have Vim in your path to setup inverse and forward search for example. 
But for earlier version consider using ```v:progname``` instead, that has been around since Vim 6.
As long as Vim is in your path, all will work even with ```v:progname```.
```
if v:version > 704 || (v:version == 704 && has('patch234')) ...
```

**Comment by chrisbra** [comment]
Thanks for reporting. I have fixed it with the latest commit.
