### ISSUE TITLE
recover#RecoverFinish() does not delete swap file

### ISSUE THREAD

**Issue by PhilRunninger** [chrisbra/Recover.vim#38]
In my [vimrc](https://github.com/PhilRunninger/my_vim_setup), I have the `set directory=$VIMHOME/tmp/swapfiles//` statement to keep my development folders clear of swap files. I am running vim 7.4.712 on MacOSX. After vim crashes, my preferred choice is to use the `Diff` in your plugin to examine the differences. When I'm done, using either `:RecoverPluginFinish` or `:RecoverPluginGet`, I think all is well. That is, until I edit the file again, and I go through the same operation. I traced it down to the `call delete(fnameescape(swapname))` statement in `recover#RecoverFinish()`. The `delete()` function is returning a -2. 

At the time the error occurred, the value of swapname is `/Users/prunninger/.vim/tmp/swapfiles//%Users%prunninger%junk%foo.txt.swp`, which `fnameescape` changes to `/Users/prunninger/.vim/tmp/swapfiles//\%Users\%prunninger\%junk\%foo.txt.swp`.

As I stated in my [StackOverflow](http://stackoverflow.com/questions/32142247/what-are-the-vimscript-delete-function-return-codes-and-their-meanings) question, I suspect bad escaping, pointing to a nonexistent file, rather than a permission issue.

**Comment by vim-ml** [comment]
So we should remove the fnameescpae()?

**Comment by chrisbra** [comment]
So removing the fnameescape() call should be safe?

**Comment by chrisbra** [comment]
Please check current head, if this works for you

**Comment by PhilRunninger** [comment]
That did the trick. Thanks for the quick response.
