### ISSUE TITLE
Bug: rubbish message in neovim

### ISSUE THREAD

**Issue by amerlyq** [chrisbra/Recover.vim#39]
Seems like it somehow messed out by reasons of migrating to shada.
Check out if it possible to fix, please. 
As 'diff' case  saved me innumerable times, but output makes sad:)
```
chdir(/home/amerlyq/aura/airy/cfg/term/vim/cfg/plugins)                             
chdir(/home/amerlyq/.vim/cfg/plugins)                                               
chdir(/home/amerlyq/aura/airy/cfg/term/vim/cfg/plugins)                             
Reading ShaDa file "/home/amerlyq/.local/share/nvim/shada/main.shada" info marks old
files^[[?1049h^[[H^[[J^[[?2004h^[[8;24;80t^[[H^[[J^[[1;1H^[[1;1H^[[?1002h^[[?1006h^[
[24;1Hchdir(/home/amerlyq/aura/airy/cfg/term/vim/cfg/plugins)^[[24;56H^[[1;24r^[[1;1
H^[[M^[[1;24r^[[24;56H^[[24;1Hchdir(/home/amerlyq/.vim/cfg/plugins)^[[1;24r^[[1;1H^[
[M^[[1;24r^[[24;38H^[[24;1Hchdir(/home/amerlyq/aura/airy/cfg/term/vim/cfg/plugins)^[
[1;24r^[[1;1H^[[M^[[1;24r^[[24;56H^[[24;1H"~/.vim/cfg/plugins/environment.yml" ^[[24
;38H^[[24;1H"~/.vim/cfg/plugins/environment.yml" 37L, 1245C^[[1;24r^[[1;1H^[[M^[[1;2
4r^[[24;48H^[[24;1HReading ShaDa file "/home/amerlyq/.local/share/nvim/shada/main.sh
ada" marks ^[[?1002h^[[?1006h^[[1;24r^[[1;1H^[[M^[[1;24r^[[24;77H^[[24;1HEntering Ex
 mode.  Type "visual" to go to Normal mode.^[[1;24r^[[1;1H^[[M^[[1;24r^[[24;55H^[[24
;1H:^[[24;2H^[[24;2H^[[24;1H^[[1;24r^[[1;1H^[[M^[[1;24r^[[24;1HWriting ShaDa file "/
home/amerlyq/.local/share/nvim/shada/main.shada"^[[24;70H^[[24;1H^[[2 q^[[?1002l^[[?
1006l^[[m^O^[[?1049l^[[?2004l                                                       
Swap and on-disk file seem to be identical
```

**Comment by chrisbra** [comment]
I am not sure, what to do with this, as I don't use neovim

**Comment by amerlyq** [comment]
Aah, I'm not sure either. Manual testing with different kind of terminal strings to fetch msg bore no results. Output don't seems like expected by next substitutions at all.
Would it be possible to make message parsing/patching optional? So only options like ```D[i]ff``` would be added, leaving message body intact?

**Comment by chrisbra** [comment]
Hi Dmytro!

On Mo, 23 Nov 2015, Dmytro Kolomoiets wrote:

> Aah, I'm not sure either. Manual testing with different kind of terminal strings to fetch msg bore no results. Output don't seems like expected by next substitutions at all.
> Would it be possible to make message parsing/patching optional? So only options like ```D[i]ff``` would be added, leaving message body intact?

Okay, I have pushed a change, that allows skipping the investigation of 
the swapfile. Set the variable 'g:RecoverPlugin_No_Check_Swapfile' to 1

Please check if this works for you.

**Comment by amerlyq** [comment]
It somehow works, however option for 'delete' swap file disappered somewhere on the way.
And I miss other info like pid/rights, but consider this as valid compromise, if original message couldn't be left intact.
Because, if I understood correctly, replacing only last two lines of case-options in message buffer isn't possible -- only rewriting buffer as whole -- therefore you used re-launching vim inside of vim to get msg?

**Comment by amerlyq** [comment]
Rather interesting results. Using ```NeoBundleLazy``` with this plugin had no sense at all (at least in my mind earlier), because the detection of a swap file must be performed for buffer from the load time and along its lifetime. But if you do it Lazy nevertheless and use source on autocmd like this:
```
if neobundle#tap('Recover.vim') "{{{
  let g:RecoverPlugin_No_Check_Swapfile = 1
  au MyAutoCmd SwapExists * nested  NeoBundleSource Recover.vim
  call neobundle#untap()
endif "}}}
```
Then on file open, it shows origin nvim message intact (instead of empty message) and new option of ```D[i]ff``` will appear under it. Voila!
It didn't fixed missed ```(d)elete``` option, though.

**Comment by chrisbra** [comment]
PID from the message is not parsed, that was the whole point of launching another vim instance in the plugin and what I understand from you was, that exactly that does not work.

Regarding the option "Delete" that is only visible, if no process with this PID exists. That is builtin to Vim, there is nothing  I can do about.
