### ISSUE TITLE
Doesn't work when opening a file with ctrl-p

### ISSUE THREAD

**Issue by zacps** [chrisbra/Recover.vim#40]
The swap file found message comes up without the options at the bottom then it asks you to press enter to continue which just opens the file. Is it possible to fix this?

**Comment by chrisbra** [comment]
Is there a simple way to reproduce the issue?

**Comment by zacps** [comment]
Create a file in vim, save. While vim is running open another instance of
vim and use ctrlp to open the file. Choose diff.

**Comment by chrisbra** [comment]
can you show the message please?

**Comment by zacps** [comment]
Sorry for the delay

![2016-09-04-124058_1366x768_scrot](https://cloud.githubusercontent.com/assets/9827696/18228308/239ddb66-729d-11e6-94b6-cbcf4df372ce.png)
![2016-09-04-124141_1366x768_scrot](https://cloud.githubusercontent.com/assets/9827696/18228309/23a2bc1c-729d-11e6-80cc-426ee80bc76b.png)

**Comment by chrisbra** [comment]
Hm, you second message shows the usual [D]iff prompt?

**Comment by zacps** [comment]
The first screen happens some of the time, some error in ctrl-p (I'm not sure if related but I haven't seen it happen without this plugin.)
The other two are what happens most of the time, the third one is what happens if you d(i)ff. Enter just opens the file and it'll warn again about a swap file on write as usual.

**Comment by crapp** [comment]
Has anything happened here? I have the same problem with fzf. Any information that could be useful?

**Comment by chrisbra** [comment]
Please create an step by step reproduction. Then I can have a look

**Comment by chrisbra** [comment]
I think, those plugins may need a `nested` somewhere in the call of their auto commands. I don't think it is a problem of my plugin. So closing.
