### ISSUE TITLE
Getting E382 Buftype Not Set error when I attempt to save

### ISSUE THREAD

**Issue by snoblenet** [chrisbra/Recover.vim#48]
Thanks for Recover.vim. I love having the option to drop into a diff window on recover.

Currently, after I align the left and right windows with `:diffget` and `:diffput`, I try to save both windows with `:wq`. However, I get a `Cannot write, 'buftype' option is set` error. The only way to save is to first `:set buftype=" "`. Am I missing something?

Also, what what be your opinion of Recover.vim automatically deleting the swap file as part of this process?

**Comment by Flurrywinde** [comment]
I just had this problem too. Why did you close this issue?

**Comment by chrisbra** [comment]
The buftype option is only set for the buffer that contains the recovered content from the swap file and does not correspond to a physical file. You need to save the other buffer
