### ISSUE TITLE
make it somehow more obvious in README that it's not `D`?

### ISSUE THREAD

**Issue by wolftune** [chrisbra/Recover.vim#51]
I kept hitting `D` trying to make this work and shocked at how it would just delete the swp instead of open a diff. Arg. Stupid me. But still, somehow adding a really obvious bold bit to the README saying "using `i`, not `D`!!!" would be appropriate for this plugin that is liable to this confusion.

Anyway, thanks, it works great!!

**Comment by chrisbra** [comment]
thanks, pushed a change. Please check.

**Comment by wolftune** [comment]
Definite improvement. I won't push on this more, but for reference, I'd write it more more like:

```
Press **i** to see the diff. (Don't press `D`! That will still *delete* the swap file!)
```

And maybe make it a bullet item to draw attention to it.

If you like these suggestions, go ahead, but anyway, I'm happy enough, and again: wonderful plugin, it ought to be built-in to Vim!

**Comment by chrisbra** [comment]
would you like to create a PR for that?

**Comment by wolftune** [comment]
I started considering chatting about the issues and explaining that I wasn't sure if my suggestion was agreed to be good etc. but I decided to not waste more time talking about it and went and revised the whole README to improve it overall. Cheers
