### ISSUE TITLE
Doesn't work if set shortmess+=F

### ISSUE THREAD

**Issue by ray851107** [chrisbra/Recover.vim#55]
The plugin does not display the dialog if I set shortmess+=F in my .vimrc
It shows a blank screen instead

**Comment by chrisbra** [comment]
Hm, I wonder what `shortmess+=F` changes, that it doesn't work anymore. It doesn't look like it disables the recovery dialog so it should still work.

**Comment by chrisbra** [comment]
looks like this is a side effect of Vim not redrawing. The same happens when using `:silent` as stated in the documentation. I don't think this plugin can work around that. I even tried adding some additional `:redraw!` commands, but that did not do anything.
