### ISSUE TITLE
doesn't recognize .swo etc

### ISSUE THREAD

**Issue by wolftune** [chrisbra/Recover.vim#56]
If there somehow are additional swap files beyond the first .swp, then after deleting the .swp, this ought to ideally see if there are other swap files also.

**Comment by chrisbra** [comment]
Recover.vim simply hooks into the existing SwapFile-Exists dialog. It cannot make changes to when that dialogue is showed, as this part is a feature of the C core of Vim. Therefore closing.

**Comment by wolftune** [comment]
gotcha, darn, oh well
