### ISSUE TITLE
Screen not shown

### ISSUE THREAD

**Issue by DerWeh** [chrisbra/Recover.vim#59]
I recently switched from `NVIM v0.2.0-1171-g4566f7c` to `NVIM v0.3.1-1-g489d32f2b`.

Now, after starting the plug-in only shows an empty screen. Pressing `i` still triggers the diff.
If I press `<ESC>` the usual info screen appears.

**Comment by chrisbra** [comment]
so when editing a file for which a swap file exists, it won't show you the Attention dialog?

**Comment by chrisbra** [comment]
(even without the plugin I mean)

**Comment by DerWeh** [comment]
It shows the dialog without the plug-in. With the plug-in it shows nothing, however the mappings still work. Pressing `<ESC>` gives you the normal dialog, which you see without the plug-in.

**Comment by chrisbra** [comment]
I would report it to the neovim devs so. I am not sure what to do with this here (or how to fix it, putting a redraw somewhere?)

**Comment by reduxionist** [comment]
This was happening to me on neovim 0.3.0 and 0.3.1, but upgrading to 0.3.2 has resolved the issue. :smile:

**Comment by Rich-YoYo** [comment]
I've just come across this problem myself. I thought it might be something to do with the lazy redraw option but after disabling that, the problem persists.
I traced the point of failure to autoload/recover.vim, line 181 - "let p = confirm(info, cmd, (delete ? 7 : 1), 'I')". If I return just before this, the normal dialogue is displayed. If I return just after this, I get the blank screen. No idea of the significance of this, but just thought I would let you know; it looks like the 'confirm' command is hanging

**Comment by chrisbra** [comment]
Hm, I guess on Vim it works well? If you insert a 
```
:redraw
:echo msg
```
right above the `let p = confirm(info, cmd, (delete ? 7 : 1), 'I')` line, does that change anything?

**Comment by Rich-YoYo** [comment]
On Mon, 21 Jan 2019 09:55:29 -0800
Christian Brabandt <notifications@github.com> wrote:

> Hm, I guess on Vim it works well? If you insert a 
> ```
> :redraw
> :echo msg
> ```
> right above the `let p = confirm(info, cmd, (delete ? 7 : 1), 'I')`
> line, does that change anything?
> 

I'm afraid that doesn't help. And yes, it works find in vim.

regards

Rich

**Comment by chrisbra** [comment]
I tested  493d80e  locally with nvim 0.2.2 and latest neovim appimage snapshot NVIM v0.3.2-909-g85761dd42 and commit 493d80e fixes it for me.
