### ISSUE TITLE
Wrong command names in recoverPlugin.txt, and confusion

### ISSUE THREAD

**Issue by gea0** [chrisbra/Recover.vim#65]
Hello, great plugin.
In `doc/recoverPlugin.txt`, I noticed some mentions of commands with "RecoveryPlugin" at the beginning, they should  start with "RecoverPlugin".

Also, I am really confused by the command "RecoverPluginGet".
The help text says:
```
Will get all changes from the recovered swapfile put them in the buffer and
finish diff mode off.
```
But it doesn't **get** anything from the swapfile.
You end up with a buffer with the regular file content.
Maybe it would be better to call it "RecoverPluginDiscard"?
Because that is what the option seems to be doing, it discards the swapfile.
Or adjust the help text to "Will get the regular on-disk version of the file and discard the swapfile"?

**Comment by chrisbra** [comment]
and another issue I did not get notified about. Sorry, I have just fixed the documentation. Thanks!
