### ISSUE TITLE
Specific Plugin Manager recommendation

### ISSUE THREAD

**Issue by BillyCroan** [chrisbra/Recover.vim#76]
> We recommend installing with a plugin manager (there are several).

Might you recommend one?  I want to install your plugin the recommended way, but perhaps I have not used a plugin manager before.  Perhaps this plugin is not available in all plugin managers?  I'm using Debian 12.

**Comment by chrisbra** [comment]
I would actually just make use of packages, e.g. simply clone into `~/.vim/packages/dist/start`

But I have heard good things about https://github.com/junegunn/vim-plug

Note: I am not using a plugin manager, so cannot recommend one.

**Comment by BillyCroan** [comment]
> $ mkdir ~/.vim/packages/dist/start -p
> $ cd ~/.vim/packages/dist/start
> /.vim/packages/dist/start$ ls
> /.vim/packages/dist/start$ git clone https://github.com/chrisbra/Recover.vim.git
> Cloning into 'Recover.vim'...
> remote: Enumerating objects: 946, done.
> remote: Counting objects: 100% (61/61), done.
> remote: Compressing objects: 100% (28/28), done.
> remote: Total 946 (delta 25), reused 54 (delta 20), pack-reused 885
> Receiving objects: 100% (946/946), 264.62 KiB | 286.00 KiB/s, done.
> Resolving deltas: 100% (420/420), done.
> me@host /.vim/packages/dist/start$ vim asdf
> me@host /.vim/packages/dist/start$ vim asdf
> Vim: Caught deadly signal TERM
> Vim: preserving files...
> Vim: Finished.
> Terminated
> ~/.vim/packages/dist/start$ vim asdf
> 

(I killed vim from another tab)  Didn't seem to work.   I should have see the compare option right?

Then I went back to this projects install instructions (the ones after the recommendation to use a plugin manager) and I followed:
~/.vim/packages/dist/start$ vim Recover.vim/Recover.vmb 
(and did the `:so %` incantation) and........
~/.vim/packages/dist/start$ vim asdf
~/.vim/packages/dist/start$ 

It works!!!! Thanks!  Hopefully this thread helps the next guy and/or gal
